deploy:
  replicas: 3
  image: 
    name: dipayanp007/nginx-se
    tag: 1.0.0
  imagePullPolicy: IfNotPresent
  port: 80
  containerName: nginx
  strategy:
    custom: true
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32000
  name: traffic

