apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  ingressClassName: kon
  rules:
  - host: nginx2.minikube.argo
    http:
      paths:
      - backend:
          service:
            name: nginx-nginx-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific

